// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: amazon.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AProduct struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          *int64  `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Description *string `protobuf:"bytes,2,req,name=description" json:"description,omitempty"`
	Count       *int32  `protobuf:"varint,3,req,name=count" json:"count,omitempty"`
}

func (x *AProduct) Reset() {
	*x = AProduct{}
	if protoimpl.UnsafeEnabled {
		mi := &file_amazon_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AProduct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AProduct) ProtoMessage() {}

func (x *AProduct) ProtoReflect() protoreflect.Message {
	mi := &file_amazon_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AProduct.ProtoReflect.Descriptor instead.
func (*AProduct) Descriptor() ([]byte, []int) {
	return file_amazon_proto_rawDescGZIP(), []int{0}
}

func (x *AProduct) GetId() int64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *AProduct) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *AProduct) GetCount() int32 {
	if x != nil && x.Count != nil {
		return *x.Count
	}
	return 0
}

type AInitWarehouse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id *int32 `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	X  *int32 `protobuf:"varint,2,req,name=x" json:"x,omitempty"`
	Y  *int32 `protobuf:"varint,3,req,name=y" json:"y,omitempty"`
}

func (x *AInitWarehouse) Reset() {
	*x = AInitWarehouse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_amazon_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AInitWarehouse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AInitWarehouse) ProtoMessage() {}

func (x *AInitWarehouse) ProtoReflect() protoreflect.Message {
	mi := &file_amazon_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AInitWarehouse.ProtoReflect.Descriptor instead.
func (*AInitWarehouse) Descriptor() ([]byte, []int) {
	return file_amazon_proto_rawDescGZIP(), []int{1}
}

func (x *AInitWarehouse) GetId() int32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *AInitWarehouse) GetX() int32 {
	if x != nil && x.X != nil {
		return *x.X
	}
	return 0
}

func (x *AInitWarehouse) GetY() int32 {
	if x != nil && x.Y != nil {
		return *x.Y
	}
	return 0
}

type AConnect struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Worldid  *int64            `protobuf:"varint,1,opt,name=worldid" json:"worldid,omitempty"`
	Initwh   []*AInitWarehouse `protobuf:"bytes,2,rep,name=initwh" json:"initwh,omitempty"`
	IsAmazon *bool             `protobuf:"varint,3,req,name=isAmazon" json:"isAmazon,omitempty"`
}

func (x *AConnect) Reset() {
	*x = AConnect{}
	if protoimpl.UnsafeEnabled {
		mi := &file_amazon_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AConnect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AConnect) ProtoMessage() {}

func (x *AConnect) ProtoReflect() protoreflect.Message {
	mi := &file_amazon_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AConnect.ProtoReflect.Descriptor instead.
func (*AConnect) Descriptor() ([]byte, []int) {
	return file_amazon_proto_rawDescGZIP(), []int{2}
}

func (x *AConnect) GetWorldid() int64 {
	if x != nil && x.Worldid != nil {
		return *x.Worldid
	}
	return 0
}

func (x *AConnect) GetInitwh() []*AInitWarehouse {
	if x != nil {
		return x.Initwh
	}
	return nil
}

func (x *AConnect) GetIsAmazon() bool {
	if x != nil && x.IsAmazon != nil {
		return *x.IsAmazon
	}
	return false
}

type AConnected struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Worldid *int64  `protobuf:"varint,1,req,name=worldid" json:"worldid,omitempty"`
	Result  *string `protobuf:"bytes,2,req,name=result" json:"result,omitempty"`
}

func (x *AConnected) Reset() {
	*x = AConnected{}
	if protoimpl.UnsafeEnabled {
		mi := &file_amazon_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AConnected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AConnected) ProtoMessage() {}

func (x *AConnected) ProtoReflect() protoreflect.Message {
	mi := &file_amazon_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AConnected.ProtoReflect.Descriptor instead.
func (*AConnected) Descriptor() ([]byte, []int) {
	return file_amazon_proto_rawDescGZIP(), []int{3}
}

func (x *AConnected) GetWorldid() int64 {
	if x != nil && x.Worldid != nil {
		return *x.Worldid
	}
	return 0
}

func (x *AConnected) GetResult() string {
	if x != nil && x.Result != nil {
		return *x.Result
	}
	return ""
}

type APack struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Whnum  *int32      `protobuf:"varint,1,req,name=whnum" json:"whnum,omitempty"`
	Things []*AProduct `protobuf:"bytes,2,rep,name=things" json:"things,omitempty"`
	Shipid *int64      `protobuf:"varint,3,req,name=shipid" json:"shipid,omitempty"`
	Seqnum *int64      `protobuf:"varint,4,req,name=seqnum" json:"seqnum,omitempty"`
}

func (x *APack) Reset() {
	*x = APack{}
	if protoimpl.UnsafeEnabled {
		mi := &file_amazon_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *APack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APack) ProtoMessage() {}

func (x *APack) ProtoReflect() protoreflect.Message {
	mi := &file_amazon_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APack.ProtoReflect.Descriptor instead.
func (*APack) Descriptor() ([]byte, []int) {
	return file_amazon_proto_rawDescGZIP(), []int{4}
}

func (x *APack) GetWhnum() int32 {
	if x != nil && x.Whnum != nil {
		return *x.Whnum
	}
	return 0
}

func (x *APack) GetThings() []*AProduct {
	if x != nil {
		return x.Things
	}
	return nil
}

func (x *APack) GetShipid() int64 {
	if x != nil && x.Shipid != nil {
		return *x.Shipid
	}
	return 0
}

func (x *APack) GetSeqnum() int64 {
	if x != nil && x.Seqnum != nil {
		return *x.Seqnum
	}
	return 0
}

type APacked struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Shipid *int64 `protobuf:"varint,1,req,name=shipid" json:"shipid,omitempty"`
	Seqnum *int64 `protobuf:"varint,2,req,name=seqnum" json:"seqnum,omitempty"`
}

func (x *APacked) Reset() {
	*x = APacked{}
	if protoimpl.UnsafeEnabled {
		mi := &file_amazon_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *APacked) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APacked) ProtoMessage() {}

func (x *APacked) ProtoReflect() protoreflect.Message {
	mi := &file_amazon_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APacked.ProtoReflect.Descriptor instead.
func (*APacked) Descriptor() ([]byte, []int) {
	return file_amazon_proto_rawDescGZIP(), []int{5}
}

func (x *APacked) GetShipid() int64 {
	if x != nil && x.Shipid != nil {
		return *x.Shipid
	}
	return 0
}

func (x *APacked) GetSeqnum() int64 {
	if x != nil && x.Seqnum != nil {
		return *x.Seqnum
	}
	return 0
}

type ALoaded struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Shipid *int64 `protobuf:"varint,1,req,name=shipid" json:"shipid,omitempty"`
	Seqnum *int64 `protobuf:"varint,2,req,name=seqnum" json:"seqnum,omitempty"`
}

func (x *ALoaded) Reset() {
	*x = ALoaded{}
	if protoimpl.UnsafeEnabled {
		mi := &file_amazon_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ALoaded) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ALoaded) ProtoMessage() {}

func (x *ALoaded) ProtoReflect() protoreflect.Message {
	mi := &file_amazon_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ALoaded.ProtoReflect.Descriptor instead.
func (*ALoaded) Descriptor() ([]byte, []int) {
	return file_amazon_proto_rawDescGZIP(), []int{6}
}

func (x *ALoaded) GetShipid() int64 {
	if x != nil && x.Shipid != nil {
		return *x.Shipid
	}
	return 0
}

func (x *ALoaded) GetSeqnum() int64 {
	if x != nil && x.Seqnum != nil {
		return *x.Seqnum
	}
	return 0
}

type APutOnTruck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Whnum   *int32 `protobuf:"varint,1,req,name=whnum" json:"whnum,omitempty"`
	Truckid *int32 `protobuf:"varint,2,req,name=truckid" json:"truckid,omitempty"`
	Shipid  *int64 `protobuf:"varint,3,req,name=shipid" json:"shipid,omitempty"`
	Seqnum  *int64 `protobuf:"varint,4,req,name=seqnum" json:"seqnum,omitempty"`
}

func (x *APutOnTruck) Reset() {
	*x = APutOnTruck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_amazon_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *APutOnTruck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APutOnTruck) ProtoMessage() {}

func (x *APutOnTruck) ProtoReflect() protoreflect.Message {
	mi := &file_amazon_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APutOnTruck.ProtoReflect.Descriptor instead.
func (*APutOnTruck) Descriptor() ([]byte, []int) {
	return file_amazon_proto_rawDescGZIP(), []int{7}
}

func (x *APutOnTruck) GetWhnum() int32 {
	if x != nil && x.Whnum != nil {
		return *x.Whnum
	}
	return 0
}

func (x *APutOnTruck) GetTruckid() int32 {
	if x != nil && x.Truckid != nil {
		return *x.Truckid
	}
	return 0
}

func (x *APutOnTruck) GetShipid() int64 {
	if x != nil && x.Shipid != nil {
		return *x.Shipid
	}
	return 0
}

func (x *APutOnTruck) GetSeqnum() int64 {
	if x != nil && x.Seqnum != nil {
		return *x.Seqnum
	}
	return 0
}

type APurchaseMore struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Whnum  *int32      `protobuf:"varint,1,req,name=whnum" json:"whnum,omitempty"`
	Things []*AProduct `protobuf:"bytes,2,rep,name=things" json:"things,omitempty"`
	Seqnum *int64      `protobuf:"varint,3,req,name=seqnum" json:"seqnum,omitempty"`
}

func (x *APurchaseMore) Reset() {
	*x = APurchaseMore{}
	if protoimpl.UnsafeEnabled {
		mi := &file_amazon_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *APurchaseMore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APurchaseMore) ProtoMessage() {}

func (x *APurchaseMore) ProtoReflect() protoreflect.Message {
	mi := &file_amazon_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APurchaseMore.ProtoReflect.Descriptor instead.
func (*APurchaseMore) Descriptor() ([]byte, []int) {
	return file_amazon_proto_rawDescGZIP(), []int{8}
}

func (x *APurchaseMore) GetWhnum() int32 {
	if x != nil && x.Whnum != nil {
		return *x.Whnum
	}
	return 0
}

func (x *APurchaseMore) GetThings() []*AProduct {
	if x != nil {
		return x.Things
	}
	return nil
}

func (x *APurchaseMore) GetSeqnum() int64 {
	if x != nil && x.Seqnum != nil {
		return *x.Seqnum
	}
	return 0
}

type AErr struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Err          *string `protobuf:"bytes,1,req,name=err" json:"err,omitempty"`
	Originseqnum *int64  `protobuf:"varint,2,req,name=originseqnum" json:"originseqnum,omitempty"`
	Seqnum       *int64  `protobuf:"varint,3,req,name=seqnum" json:"seqnum,omitempty"`
}

func (x *AErr) Reset() {
	*x = AErr{}
	if protoimpl.UnsafeEnabled {
		mi := &file_amazon_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AErr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AErr) ProtoMessage() {}

func (x *AErr) ProtoReflect() protoreflect.Message {
	mi := &file_amazon_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AErr.ProtoReflect.Descriptor instead.
func (*AErr) Descriptor() ([]byte, []int) {
	return file_amazon_proto_rawDescGZIP(), []int{9}
}

func (x *AErr) GetErr() string {
	if x != nil && x.Err != nil {
		return *x.Err
	}
	return ""
}

func (x *AErr) GetOriginseqnum() int64 {
	if x != nil && x.Originseqnum != nil {
		return *x.Originseqnum
	}
	return 0
}

func (x *AErr) GetSeqnum() int64 {
	if x != nil && x.Seqnum != nil {
		return *x.Seqnum
	}
	return 0
}

type AQuery struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Packageid *int64 `protobuf:"varint,1,req,name=packageid" json:"packageid,omitempty"`
	Seqnum    *int64 `protobuf:"varint,2,req,name=seqnum" json:"seqnum,omitempty"`
}

func (x *AQuery) Reset() {
	*x = AQuery{}
	if protoimpl.UnsafeEnabled {
		mi := &file_amazon_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AQuery) ProtoMessage() {}

func (x *AQuery) ProtoReflect() protoreflect.Message {
	mi := &file_amazon_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AQuery.ProtoReflect.Descriptor instead.
func (*AQuery) Descriptor() ([]byte, []int) {
	return file_amazon_proto_rawDescGZIP(), []int{10}
}

func (x *AQuery) GetPackageid() int64 {
	if x != nil && x.Packageid != nil {
		return *x.Packageid
	}
	return 0
}

func (x *AQuery) GetSeqnum() int64 {
	if x != nil && x.Seqnum != nil {
		return *x.Seqnum
	}
	return 0
}

type APackage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Packageid *int64  `protobuf:"varint,1,req,name=packageid" json:"packageid,omitempty"`
	Status    *string `protobuf:"bytes,2,req,name=status" json:"status,omitempty"`
	Seqnum    *int64  `protobuf:"varint,3,req,name=seqnum" json:"seqnum,omitempty"`
}

func (x *APackage) Reset() {
	*x = APackage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_amazon_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *APackage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APackage) ProtoMessage() {}

func (x *APackage) ProtoReflect() protoreflect.Message {
	mi := &file_amazon_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APackage.ProtoReflect.Descriptor instead.
func (*APackage) Descriptor() ([]byte, []int) {
	return file_amazon_proto_rawDescGZIP(), []int{11}
}

func (x *APackage) GetPackageid() int64 {
	if x != nil && x.Packageid != nil {
		return *x.Packageid
	}
	return 0
}

func (x *APackage) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

func (x *APackage) GetSeqnum() int64 {
	if x != nil && x.Seqnum != nil {
		return *x.Seqnum
	}
	return 0
}

type ACommands struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Buy        []*APurchaseMore `protobuf:"bytes,1,rep,name=buy" json:"buy,omitempty"`
	Topack     []*APack         `protobuf:"bytes,2,rep,name=topack" json:"topack,omitempty"`
	Load       []*APutOnTruck   `protobuf:"bytes,3,rep,name=load" json:"load,omitempty"`
	Queries    []*AQuery        `protobuf:"bytes,4,rep,name=queries" json:"queries,omitempty"`
	Simspeed   *uint32          `protobuf:"varint,5,opt,name=simspeed" json:"simspeed,omitempty"`
	Disconnect *bool            `protobuf:"varint,6,opt,name=disconnect" json:"disconnect,omitempty"`
	Acks       []int64          `protobuf:"varint,7,rep,name=acks" json:"acks,omitempty"`
}

func (x *ACommands) Reset() {
	*x = ACommands{}
	if protoimpl.UnsafeEnabled {
		mi := &file_amazon_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ACommands) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ACommands) ProtoMessage() {}

func (x *ACommands) ProtoReflect() protoreflect.Message {
	mi := &file_amazon_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ACommands.ProtoReflect.Descriptor instead.
func (*ACommands) Descriptor() ([]byte, []int) {
	return file_amazon_proto_rawDescGZIP(), []int{12}
}

func (x *ACommands) GetBuy() []*APurchaseMore {
	if x != nil {
		return x.Buy
	}
	return nil
}

func (x *ACommands) GetTopack() []*APack {
	if x != nil {
		return x.Topack
	}
	return nil
}

func (x *ACommands) GetLoad() []*APutOnTruck {
	if x != nil {
		return x.Load
	}
	return nil
}

func (x *ACommands) GetQueries() []*AQuery {
	if x != nil {
		return x.Queries
	}
	return nil
}

func (x *ACommands) GetSimspeed() uint32 {
	if x != nil && x.Simspeed != nil {
		return *x.Simspeed
	}
	return 0
}

func (x *ACommands) GetDisconnect() bool {
	if x != nil && x.Disconnect != nil {
		return *x.Disconnect
	}
	return false
}

func (x *ACommands) GetAcks() []int64 {
	if x != nil {
		return x.Acks
	}
	return nil
}

type AResponses struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Arrived       []*APurchaseMore `protobuf:"bytes,1,rep,name=arrived" json:"arrived,omitempty"`
	Ready         []*APacked       `protobuf:"bytes,2,rep,name=ready" json:"ready,omitempty"`
	Loaded        []*ALoaded       `protobuf:"bytes,3,rep,name=loaded" json:"loaded,omitempty"`
	Finished      *bool            `protobuf:"varint,4,opt,name=finished" json:"finished,omitempty"`
	Error         []*AErr          `protobuf:"bytes,5,rep,name=error" json:"error,omitempty"`
	Acks          []int64          `protobuf:"varint,6,rep,name=acks" json:"acks,omitempty"`
	Packagestatus []*APackage      `protobuf:"bytes,7,rep,name=packagestatus" json:"packagestatus,omitempty"`
}

func (x *AResponses) Reset() {
	*x = AResponses{}
	if protoimpl.UnsafeEnabled {
		mi := &file_amazon_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AResponses) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AResponses) ProtoMessage() {}

func (x *AResponses) ProtoReflect() protoreflect.Message {
	mi := &file_amazon_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AResponses.ProtoReflect.Descriptor instead.
func (*AResponses) Descriptor() ([]byte, []int) {
	return file_amazon_proto_rawDescGZIP(), []int{13}
}

func (x *AResponses) GetArrived() []*APurchaseMore {
	if x != nil {
		return x.Arrived
	}
	return nil
}

func (x *AResponses) GetReady() []*APacked {
	if x != nil {
		return x.Ready
	}
	return nil
}

func (x *AResponses) GetLoaded() []*ALoaded {
	if x != nil {
		return x.Loaded
	}
	return nil
}

func (x *AResponses) GetFinished() bool {
	if x != nil && x.Finished != nil {
		return *x.Finished
	}
	return false
}

func (x *AResponses) GetError() []*AErr {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *AResponses) GetAcks() []int64 {
	if x != nil {
		return x.Acks
	}
	return nil
}

func (x *AResponses) GetPackagestatus() []*APackage {
	if x != nil {
		return x.Packagestatus
	}
	return nil
}

var File_amazon_proto protoreflect.FileDescriptor

var file_amazon_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x61, 0x6d, 0x61, 0x7a, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02,
	0x70, 0x62, 0x22, 0x52, 0x0a, 0x08, 0x41, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x02, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x20,
	0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20,
	0x02, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x02, 0x28, 0x05, 0x52,
	0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x3c, 0x0a, 0x0e, 0x41, 0x49, 0x6e, 0x69, 0x74, 0x57,
	0x61, 0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x02, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x02, 0x20,
	0x02, 0x28, 0x05, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x03, 0x20, 0x02, 0x28,
	0x05, 0x52, 0x01, 0x79, 0x22, 0x6c, 0x0a, 0x08, 0x41, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74,
	0x12, 0x18, 0x0a, 0x07, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x07, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x69, 0x64, 0x12, 0x2a, 0x0a, 0x06, 0x69, 0x6e,
	0x69, 0x74, 0x77, 0x68, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x62, 0x2e,
	0x41, 0x49, 0x6e, 0x69, 0x74, 0x57, 0x61, 0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x52, 0x06,
	0x69, 0x6e, 0x69, 0x74, 0x77, 0x68, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x73, 0x41, 0x6d, 0x61, 0x7a,
	0x6f, 0x6e, 0x18, 0x03, 0x20, 0x02, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x41, 0x6d, 0x61, 0x7a,
	0x6f, 0x6e, 0x22, 0x3e, 0x0a, 0x0a, 0x41, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x65, 0x64,
	0x12, 0x18, 0x0a, 0x07, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x69, 0x64, 0x18, 0x01, 0x20, 0x02, 0x28,
	0x03, 0x52, 0x07, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x18, 0x02, 0x20, 0x02, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x22, 0x73, 0x0a, 0x05, 0x41, 0x50, 0x61, 0x63, 0x6b, 0x12, 0x14, 0x0a, 0x05, 0x77,
	0x68, 0x6e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x02, 0x28, 0x05, 0x52, 0x05, 0x77, 0x68, 0x6e, 0x75,
	0x6d, 0x12, 0x24, 0x0a, 0x06, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52,
	0x06, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x68, 0x69, 0x70, 0x69,
	0x64, 0x18, 0x03, 0x20, 0x02, 0x28, 0x03, 0x52, 0x06, 0x73, 0x68, 0x69, 0x70, 0x69, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x65, 0x71, 0x6e, 0x75, 0x6d, 0x18, 0x04, 0x20, 0x02, 0x28, 0x03, 0x52,
	0x06, 0x73, 0x65, 0x71, 0x6e, 0x75, 0x6d, 0x22, 0x39, 0x0a, 0x07, 0x41, 0x50, 0x61, 0x63, 0x6b,
	0x65, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x68, 0x69, 0x70, 0x69, 0x64, 0x18, 0x01, 0x20, 0x02,
	0x28, 0x03, 0x52, 0x06, 0x73, 0x68, 0x69, 0x70, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65,
	0x71, 0x6e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x02, 0x28, 0x03, 0x52, 0x06, 0x73, 0x65, 0x71, 0x6e,
	0x75, 0x6d, 0x22, 0x39, 0x0a, 0x07, 0x41, 0x4c, 0x6f, 0x61, 0x64, 0x65, 0x64, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x68, 0x69, 0x70, 0x69, 0x64, 0x18, 0x01, 0x20, 0x02, 0x28, 0x03, 0x52, 0x06, 0x73,
	0x68, 0x69, 0x70, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x71, 0x6e, 0x75, 0x6d, 0x18,
	0x02, 0x20, 0x02, 0x28, 0x03, 0x52, 0x06, 0x73, 0x65, 0x71, 0x6e, 0x75, 0x6d, 0x22, 0x6d, 0x0a,
	0x0b, 0x41, 0x50, 0x75, 0x74, 0x4f, 0x6e, 0x54, 0x72, 0x75, 0x63, 0x6b, 0x12, 0x14, 0x0a, 0x05,
	0x77, 0x68, 0x6e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x02, 0x28, 0x05, 0x52, 0x05, 0x77, 0x68, 0x6e,
	0x75, 0x6d, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x72, 0x75, 0x63, 0x6b, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x02, 0x28, 0x05, 0x52, 0x07, 0x74, 0x72, 0x75, 0x63, 0x6b, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x68, 0x69, 0x70, 0x69, 0x64, 0x18, 0x03, 0x20, 0x02, 0x28, 0x03, 0x52, 0x06, 0x73, 0x68,
	0x69, 0x70, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x71, 0x6e, 0x75, 0x6d, 0x18, 0x04,
	0x20, 0x02, 0x28, 0x03, 0x52, 0x06, 0x73, 0x65, 0x71, 0x6e, 0x75, 0x6d, 0x22, 0x63, 0x0a, 0x0d,
	0x41, 0x50, 0x75, 0x72, 0x63, 0x68, 0x61, 0x73, 0x65, 0x4d, 0x6f, 0x72, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x77, 0x68, 0x6e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x02, 0x28, 0x05, 0x52, 0x05, 0x77, 0x68,
	0x6e, 0x75, 0x6d, 0x12, 0x24, 0x0a, 0x06, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x52, 0x06, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x71,
	0x6e, 0x75, 0x6d, 0x18, 0x03, 0x20, 0x02, 0x28, 0x03, 0x52, 0x06, 0x73, 0x65, 0x71, 0x6e, 0x75,
	0x6d, 0x22, 0x54, 0x0a, 0x04, 0x41, 0x45, 0x72, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x72, 0x72,
	0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x03, 0x65, 0x72, 0x72, 0x12, 0x22, 0x0a, 0x0c, 0x6f,
	0x72, 0x69, 0x67, 0x69, 0x6e, 0x73, 0x65, 0x71, 0x6e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x02, 0x28,
	0x03, 0x52, 0x0c, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x73, 0x65, 0x71, 0x6e, 0x75, 0x6d, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x65, 0x71, 0x6e, 0x75, 0x6d, 0x18, 0x03, 0x20, 0x02, 0x28, 0x03, 0x52,
	0x06, 0x73, 0x65, 0x71, 0x6e, 0x75, 0x6d, 0x22, 0x3e, 0x0a, 0x06, 0x41, 0x51, 0x75, 0x65, 0x72,
	0x79, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x02, 0x28, 0x03, 0x52, 0x09, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x69, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x65, 0x71, 0x6e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x02, 0x28, 0x03, 0x52,
	0x06, 0x73, 0x65, 0x71, 0x6e, 0x75, 0x6d, 0x22, 0x58, 0x0a, 0x08, 0x41, 0x50, 0x61, 0x63, 0x6b,
	0x61, 0x67, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x02, 0x28, 0x03, 0x52, 0x09, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x69,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x02, 0x28,
	0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x71,
	0x6e, 0x75, 0x6d, 0x18, 0x03, 0x20, 0x02, 0x28, 0x03, 0x52, 0x06, 0x73, 0x65, 0x71, 0x6e, 0x75,
	0x6d, 0x22, 0xee, 0x01, 0x0a, 0x09, 0x41, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x12,
	0x23, 0x0a, 0x03, 0x62, 0x75, 0x79, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70,
	0x62, 0x2e, 0x41, 0x50, 0x75, 0x72, 0x63, 0x68, 0x61, 0x73, 0x65, 0x4d, 0x6f, 0x72, 0x65, 0x52,
	0x03, 0x62, 0x75, 0x79, 0x12, 0x21, 0x0a, 0x06, 0x74, 0x6f, 0x70, 0x61, 0x63, 0x6b, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x50, 0x61, 0x63, 0x6b, 0x52,
	0x06, 0x74, 0x6f, 0x70, 0x61, 0x63, 0x6b, 0x12, 0x23, 0x0a, 0x04, 0x6c, 0x6f, 0x61, 0x64, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x50, 0x75, 0x74, 0x4f,
	0x6e, 0x54, 0x72, 0x75, 0x63, 0x6b, 0x52, 0x04, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x24, 0x0a, 0x07,
	0x71, 0x75, 0x65, 0x72, 0x69, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e,
	0x70, 0x62, 0x2e, 0x41, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x07, 0x71, 0x75, 0x65, 0x72, 0x69,
	0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x69, 0x6d, 0x73, 0x70, 0x65, 0x65, 0x64, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x73, 0x69, 0x6d, 0x73, 0x70, 0x65, 0x65, 0x64, 0x12, 0x1e,
	0x0a, 0x0a, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x0a, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x61, 0x63, 0x6b, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x03, 0x52, 0x04, 0x61, 0x63,
	0x6b, 0x73, 0x22, 0x85, 0x02, 0x0a, 0x0a, 0x41, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x73, 0x12, 0x2b, 0x0a, 0x07, 0x61, 0x72, 0x72, 0x69, 0x76, 0x65, 0x64, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x50, 0x75, 0x72, 0x63, 0x68, 0x61, 0x73,
	0x65, 0x4d, 0x6f, 0x72, 0x65, 0x52, 0x07, 0x61, 0x72, 0x72, 0x69, 0x76, 0x65, 0x64, 0x12, 0x21,
	0x0a, 0x05, 0x72, 0x65, 0x61, 0x64, 0x79, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e,
	0x70, 0x62, 0x2e, 0x41, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x64, 0x52, 0x05, 0x72, 0x65, 0x61, 0x64,
	0x79, 0x12, 0x23, 0x0a, 0x06, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x4c, 0x6f, 0x61, 0x64, 0x65, 0x64, 0x52, 0x06,
	0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68,
	0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68,
	0x65, 0x64, 0x12, 0x1e, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x05, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x45, 0x72, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x63, 0x6b, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x03,
	0x52, 0x04, 0x61, 0x63, 0x6b, 0x73, 0x12, 0x32, 0x0a, 0x0d, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67,
	0x65, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e,
	0x70, 0x62, 0x2e, 0x41, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x52, 0x0d, 0x70, 0x61, 0x63,
	0x6b, 0x61, 0x67, 0x65, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x42, 0x03, 0x5a, 0x01, 0x2e,
}

var (
	file_amazon_proto_rawDescOnce sync.Once
	file_amazon_proto_rawDescData = file_amazon_proto_rawDesc
)

func file_amazon_proto_rawDescGZIP() []byte {
	file_amazon_proto_rawDescOnce.Do(func() {
		file_amazon_proto_rawDescData = protoimpl.X.CompressGZIP(file_amazon_proto_rawDescData)
	})
	return file_amazon_proto_rawDescData
}

var file_amazon_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_amazon_proto_goTypes = []interface{}{
	(*AProduct)(nil),       // 0: pb.AProduct
	(*AInitWarehouse)(nil), // 1: pb.AInitWarehouse
	(*AConnect)(nil),       // 2: pb.AConnect
	(*AConnected)(nil),     // 3: pb.AConnected
	(*APack)(nil),          // 4: pb.APack
	(*APacked)(nil),        // 5: pb.APacked
	(*ALoaded)(nil),        // 6: pb.ALoaded
	(*APutOnTruck)(nil),    // 7: pb.APutOnTruck
	(*APurchaseMore)(nil),  // 8: pb.APurchaseMore
	(*AErr)(nil),           // 9: pb.AErr
	(*AQuery)(nil),         // 10: pb.AQuery
	(*APackage)(nil),       // 11: pb.APackage
	(*ACommands)(nil),      // 12: pb.ACommands
	(*AResponses)(nil),     // 13: pb.AResponses
}
var file_amazon_proto_depIdxs = []int32{
	1,  // 0: pb.AConnect.initwh:type_name -> pb.AInitWarehouse
	0,  // 1: pb.APack.things:type_name -> pb.AProduct
	0,  // 2: pb.APurchaseMore.things:type_name -> pb.AProduct
	8,  // 3: pb.ACommands.buy:type_name -> pb.APurchaseMore
	4,  // 4: pb.ACommands.topack:type_name -> pb.APack
	7,  // 5: pb.ACommands.load:type_name -> pb.APutOnTruck
	10, // 6: pb.ACommands.queries:type_name -> pb.AQuery
	8,  // 7: pb.AResponses.arrived:type_name -> pb.APurchaseMore
	5,  // 8: pb.AResponses.ready:type_name -> pb.APacked
	6,  // 9: pb.AResponses.loaded:type_name -> pb.ALoaded
	9,  // 10: pb.AResponses.error:type_name -> pb.AErr
	11, // 11: pb.AResponses.packagestatus:type_name -> pb.APackage
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_amazon_proto_init() }
func file_amazon_proto_init() {
	if File_amazon_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_amazon_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AProduct); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_amazon_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AInitWarehouse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_amazon_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AConnect); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_amazon_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AConnected); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_amazon_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*APack); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_amazon_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*APacked); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_amazon_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ALoaded); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_amazon_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*APutOnTruck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_amazon_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*APurchaseMore); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_amazon_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AErr); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_amazon_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AQuery); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_amazon_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*APackage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_amazon_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ACommands); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_amazon_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AResponses); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_amazon_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_amazon_proto_goTypes,
		DependencyIndexes: file_amazon_proto_depIdxs,
		MessageInfos:      file_amazon_proto_msgTypes,
	}.Build()
	File_amazon_proto = out.File
	file_amazon_proto_rawDesc = nil
	file_amazon_proto_goTypes = nil
	file_amazon_proto_depIdxs = nil
}
