// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: ua.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// request
type AUCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PickupRequests  []*AUPickupRequest  `protobuf:"bytes,1,rep,name=pickupRequests" json:"pickupRequests,omitempty"`
	DeliverRequests []*AUDeliverRequest `protobuf:"bytes,2,rep,name=deliverRequests" json:"deliverRequests,omitempty"`
	Acks            []int64             `protobuf:"varint,3,rep,name=acks" json:"acks,omitempty"`
	Error           []*Err              `protobuf:"bytes,4,rep,name=error" json:"error,omitempty"`
}

func (x *AUCommand) Reset() {
	*x = AUCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ua_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AUCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AUCommand) ProtoMessage() {}

func (x *AUCommand) ProtoReflect() protoreflect.Message {
	mi := &file_ua_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AUCommand.ProtoReflect.Descriptor instead.
func (*AUCommand) Descriptor() ([]byte, []int) {
	return file_ua_proto_rawDescGZIP(), []int{0}
}

func (x *AUCommand) GetPickupRequests() []*AUPickupRequest {
	if x != nil {
		return x.PickupRequests
	}
	return nil
}

func (x *AUCommand) GetDeliverRequests() []*AUDeliverRequest {
	if x != nil {
		return x.DeliverRequests
	}
	return nil
}

func (x *AUCommand) GetAcks() []int64 {
	if x != nil {
		return x.Acks
	}
	return nil
}

func (x *AUCommand) GetError() []*Err {
	if x != nil {
		return x.Error
	}
	return nil
}

// response
type UACommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LoadRequests []*UALoadRequest `protobuf:"bytes,1,rep,name=loadRequests" json:"loadRequests,omitempty"`
	Delivered    []*UADelivered   `protobuf:"bytes,2,rep,name=delivered" json:"delivered,omitempty"`
	Acks         []int64          `protobuf:"varint,3,rep,name=acks" json:"acks,omitempty"`
	Error        []*Err           `protobuf:"bytes,4,rep,name=error" json:"error,omitempty"`
}

func (x *UACommand) Reset() {
	*x = UACommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ua_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UACommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UACommand) ProtoMessage() {}

func (x *UACommand) ProtoReflect() protoreflect.Message {
	mi := &file_ua_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UACommand.ProtoReflect.Descriptor instead.
func (*UACommand) Descriptor() ([]byte, []int) {
	return file_ua_proto_rawDescGZIP(), []int{1}
}

func (x *UACommand) GetLoadRequests() []*UALoadRequest {
	if x != nil {
		return x.LoadRequests
	}
	return nil
}

func (x *UACommand) GetDelivered() []*UADelivered {
	if x != nil {
		return x.Delivered
	}
	return nil
}

func (x *UACommand) GetAcks() []int64 {
	if x != nil {
		return x.Acks
	}
	return nil
}

func (x *UACommand) GetError() []*Err {
	if x != nil {
		return x.Error
	}
	return nil
}

// UPS to Amazon: UPS creates a world for Amazon to connect to
type UAstart struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Worldid *int64 `protobuf:"varint,1,req,name=worldid" json:"worldid,omitempty"`
	Seqnum  *int64 `protobuf:"varint,2,req,name=seqnum" json:"seqnum,omitempty"`
}

func (x *UAstart) Reset() {
	*x = UAstart{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ua_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UAstart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UAstart) ProtoMessage() {}

func (x *UAstart) ProtoReflect() protoreflect.Message {
	mi := &file_ua_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UAstart.ProtoReflect.Descriptor instead.
func (*UAstart) Descriptor() ([]byte, []int) {
	return file_ua_proto_rawDescGZIP(), []int{2}
}

func (x *UAstart) GetWorldid() int64 {
	if x != nil && x.Worldid != nil {
		return *x.Worldid
	}
	return 0
}

func (x *UAstart) GetSeqnum() int64 {
	if x != nil && x.Seqnum != nil {
		return *x.Seqnum
	}
	return 0
}

// Amazon to UPS: when Amazon received a Buy command, it send APickupRequest to UPS to prepare a truck sent to target warehouse
type AUPickupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SeqNum       *int64  `protobuf:"varint,1,req,name=seqNum" json:"seqNum,omitempty"`
	ShipId       *int64  `protobuf:"varint,2,req,name=shipId" json:"shipId,omitempty"`
	WarehouseId  *int32  `protobuf:"varint,3,req,name=warehouseId" json:"warehouseId,omitempty"`
	X            *int32  `protobuf:"varint,4,req,name=x" json:"x,omitempty"` // location of the warehouse
	Y            *int32  `protobuf:"varint,5,req,name=y" json:"y,omitempty"` // location of the warehouse
	DestinationX *int32  `protobuf:"varint,6,req,name=destinationX" json:"destinationX,omitempty"`
	DestinationY *int32  `protobuf:"varint,7,req,name=destinationY" json:"destinationY,omitempty"`
	UpsName      *string `protobuf:"bytes,8,opt,name=upsName" json:"upsName,omitempty"`
	Items        *string `protobuf:"bytes,9,req,name=items" json:"items,omitempty"`
}

func (x *AUPickupRequest) Reset() {
	*x = AUPickupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ua_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AUPickupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AUPickupRequest) ProtoMessage() {}

func (x *AUPickupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ua_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AUPickupRequest.ProtoReflect.Descriptor instead.
func (*AUPickupRequest) Descriptor() ([]byte, []int) {
	return file_ua_proto_rawDescGZIP(), []int{3}
}

func (x *AUPickupRequest) GetSeqNum() int64 {
	if x != nil && x.SeqNum != nil {
		return *x.SeqNum
	}
	return 0
}

func (x *AUPickupRequest) GetShipId() int64 {
	if x != nil && x.ShipId != nil {
		return *x.ShipId
	}
	return 0
}

func (x *AUPickupRequest) GetWarehouseId() int32 {
	if x != nil && x.WarehouseId != nil {
		return *x.WarehouseId
	}
	return 0
}

func (x *AUPickupRequest) GetX() int32 {
	if x != nil && x.X != nil {
		return *x.X
	}
	return 0
}

func (x *AUPickupRequest) GetY() int32 {
	if x != nil && x.Y != nil {
		return *x.Y
	}
	return 0
}

func (x *AUPickupRequest) GetDestinationX() int32 {
	if x != nil && x.DestinationX != nil {
		return *x.DestinationX
	}
	return 0
}

func (x *AUPickupRequest) GetDestinationY() int32 {
	if x != nil && x.DestinationY != nil {
		return *x.DestinationY
	}
	return 0
}

func (x *AUPickupRequest) GetUpsName() string {
	if x != nil && x.UpsName != nil {
		return *x.UpsName
	}
	return ""
}

func (x *AUPickupRequest) GetItems() string {
	if x != nil && x.Items != nil {
		return *x.Items
	}
	return ""
}

// U -> A Arrived, ready to load
type UALoadRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SeqNum  *int64 `protobuf:"varint,1,req,name=seqNum" json:"seqNum,omitempty"`
	TruckId *int32 `protobuf:"varint,2,req,name=truckId" json:"truckId,omitempty"`
	ShipId  *int64 `protobuf:"varint,3,req,name=shipId" json:"shipId,omitempty"`
}

func (x *UALoadRequest) Reset() {
	*x = UALoadRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ua_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UALoadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UALoadRequest) ProtoMessage() {}

func (x *UALoadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ua_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UALoadRequest.ProtoReflect.Descriptor instead.
func (*UALoadRequest) Descriptor() ([]byte, []int) {
	return file_ua_proto_rawDescGZIP(), []int{4}
}

func (x *UALoadRequest) GetSeqNum() int64 {
	if x != nil && x.SeqNum != nil {
		return *x.SeqNum
	}
	return 0
}

func (x *UALoadRequest) GetTruckId() int32 {
	if x != nil && x.TruckId != nil {
		return *x.TruckId
	}
	return 0
}

func (x *UALoadRequest) GetShipId() int64 {
	if x != nil && x.ShipId != nil {
		return *x.ShipId
	}
	return 0
}

// A -> U: when all ready, make UPS deliver the package
type AUDeliverRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SeqNum *int64 `protobuf:"varint,1,req,name=seqNum" json:"seqNum,omitempty"`
	ShipId *int64 `protobuf:"varint,2,req,name=shipId" json:"shipId,omitempty"`
}

func (x *AUDeliverRequest) Reset() {
	*x = AUDeliverRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ua_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AUDeliverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AUDeliverRequest) ProtoMessage() {}

func (x *AUDeliverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ua_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AUDeliverRequest.ProtoReflect.Descriptor instead.
func (*AUDeliverRequest) Descriptor() ([]byte, []int) {
	return file_ua_proto_rawDescGZIP(), []int{5}
}

func (x *AUDeliverRequest) GetSeqNum() int64 {
	if x != nil && x.SeqNum != nil {
		return *x.SeqNum
	}
	return 0
}

func (x *AUDeliverRequest) GetShipId() int64 {
	if x != nil && x.ShipId != nil {
		return *x.ShipId
	}
	return 0
}

// U -> A: delivered
type UADelivered struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SeqNum *int64 `protobuf:"varint,1,req,name=seqNum" json:"seqNum,omitempty"`
	ShipId *int64 `protobuf:"varint,2,req,name=shipId" json:"shipId,omitempty"`
}

func (x *UADelivered) Reset() {
	*x = UADelivered{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ua_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UADelivered) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UADelivered) ProtoMessage() {}

func (x *UADelivered) ProtoReflect() protoreflect.Message {
	mi := &file_ua_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UADelivered.ProtoReflect.Descriptor instead.
func (*UADelivered) Descriptor() ([]byte, []int) {
	return file_ua_proto_rawDescGZIP(), []int{6}
}

func (x *UADelivered) GetSeqNum() int64 {
	if x != nil && x.SeqNum != nil {
		return *x.SeqNum
	}
	return 0
}

func (x *UADelivered) GetShipId() int64 {
	if x != nil && x.ShipId != nil {
		return *x.ShipId
	}
	return 0
}

type Err struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Err          *string `protobuf:"bytes,1,req,name=err" json:"err,omitempty"`
	OriginSeqNum *int64  `protobuf:"varint,2,req,name=originSeqNum" json:"originSeqNum,omitempty"`
	SeqNum       *int64  `protobuf:"varint,3,req,name=seqNum" json:"seqNum,omitempty"`
}

func (x *Err) Reset() {
	*x = Err{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ua_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Err) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Err) ProtoMessage() {}

func (x *Err) ProtoReflect() protoreflect.Message {
	mi := &file_ua_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Err.ProtoReflect.Descriptor instead.
func (*Err) Descriptor() ([]byte, []int) {
	return file_ua_proto_rawDescGZIP(), []int{7}
}

func (x *Err) GetErr() string {
	if x != nil && x.Err != nil {
		return *x.Err
	}
	return ""
}

func (x *Err) GetOriginSeqNum() int64 {
	if x != nil && x.OriginSeqNum != nil {
		return *x.OriginSeqNum
	}
	return 0
}

func (x *Err) GetSeqNum() int64 {
	if x != nil && x.SeqNum != nil {
		return *x.SeqNum
	}
	return 0
}

var File_ua_proto protoreflect.FileDescriptor

var file_ua_proto_rawDesc = []byte{
	0x0a, 0x08, 0x75, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0xbb,
	0x01, 0x0a, 0x09, 0x41, 0x55, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x3b, 0x0a, 0x0e,
	0x70, 0x69, 0x63, 0x6b, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x55, 0x50, 0x69, 0x63, 0x6b,
	0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x0e, 0x70, 0x69, 0x63, 0x6b, 0x75,
	0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x12, 0x3e, 0x0a, 0x0f, 0x64, 0x65, 0x6c,
	0x69, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x55, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x0f, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x63, 0x6b,
	0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x03, 0x52, 0x04, 0x61, 0x63, 0x6b, 0x73, 0x12, 0x1d, 0x0a,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x70,
	0x62, 0x2e, 0x45, 0x72, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0xa4, 0x01, 0x0a,
	0x09, 0x55, 0x41, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x35, 0x0a, 0x0c, 0x6c, 0x6f,
	0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x55, 0x41, 0x4c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x52, 0x0c, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x73, 0x12, 0x2d, 0x0a, 0x09, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x65, 0x64, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x55, 0x41, 0x44, 0x65, 0x6c, 0x69,
	0x76, 0x65, 0x72, 0x65, 0x64, 0x52, 0x09, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x65, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x61, 0x63, 0x6b, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x03, 0x52, 0x04,
	0x61, 0x63, 0x6b, 0x73, 0x12, 0x1d, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x04, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x70, 0x62, 0x2e, 0x45, 0x72, 0x72, 0x52, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x22, 0x3b, 0x0a, 0x07, 0x55, 0x41, 0x73, 0x74, 0x61, 0x72, 0x74, 0x12, 0x18,
	0x0a, 0x07, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x69, 0x64, 0x18, 0x01, 0x20, 0x02, 0x28, 0x03, 0x52,
	0x07, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x71, 0x6e,
	0x75, 0x6d, 0x18, 0x02, 0x20, 0x02, 0x28, 0x03, 0x52, 0x06, 0x73, 0x65, 0x71, 0x6e, 0x75, 0x6d,
	0x22, 0xf7, 0x01, 0x0a, 0x0f, 0x41, 0x55, 0x50, 0x69, 0x63, 0x6b, 0x75, 0x70, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x71, 0x4e, 0x75, 0x6d, 0x18, 0x01,
	0x20, 0x02, 0x28, 0x03, 0x52, 0x06, 0x73, 0x65, 0x71, 0x4e, 0x75, 0x6d, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x68, 0x69, 0x70, 0x49, 0x64, 0x18, 0x02, 0x20, 0x02, 0x28, 0x03, 0x52, 0x06, 0x73, 0x68,
	0x69, 0x70, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x77, 0x61, 0x72, 0x65, 0x68, 0x6f, 0x75, 0x73,
	0x65, 0x49, 0x64, 0x18, 0x03, 0x20, 0x02, 0x28, 0x05, 0x52, 0x0b, 0x77, 0x61, 0x72, 0x65, 0x68,
	0x6f, 0x75, 0x73, 0x65, 0x49, 0x64, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x04, 0x20, 0x02, 0x28,
	0x05, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x05, 0x20, 0x02, 0x28, 0x05, 0x52,
	0x01, 0x79, 0x12, 0x22, 0x0a, 0x0c, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x58, 0x18, 0x06, 0x20, 0x02, 0x28, 0x05, 0x52, 0x0c, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x58, 0x12, 0x22, 0x0a, 0x0c, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x59, 0x18, 0x07, 0x20, 0x02, 0x28, 0x05, 0x52, 0x0c, 0x64, 0x65,
	0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x59, 0x12, 0x18, 0x0a, 0x07, 0x75, 0x70,
	0x73, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x75, 0x70, 0x73,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x09, 0x20,
	0x02, 0x28, 0x09, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x59, 0x0a, 0x0d, 0x55, 0x41,
	0x4c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x65, 0x71, 0x4e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x02, 0x28, 0x03, 0x52, 0x06, 0x73, 0x65, 0x71,
	0x4e, 0x75, 0x6d, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x72, 0x75, 0x63, 0x6b, 0x49, 0x64, 0x18, 0x02,
	0x20, 0x02, 0x28, 0x05, 0x52, 0x07, 0x74, 0x72, 0x75, 0x63, 0x6b, 0x49, 0x64, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x68, 0x69, 0x70, 0x49, 0x64, 0x18, 0x03, 0x20, 0x02, 0x28, 0x03, 0x52, 0x06, 0x73,
	0x68, 0x69, 0x70, 0x49, 0x64, 0x22, 0x42, 0x0a, 0x10, 0x41, 0x55, 0x44, 0x65, 0x6c, 0x69, 0x76,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x71,
	0x4e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x02, 0x28, 0x03, 0x52, 0x06, 0x73, 0x65, 0x71, 0x4e, 0x75,
	0x6d, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x68, 0x69, 0x70, 0x49, 0x64, 0x18, 0x02, 0x20, 0x02, 0x28,
	0x03, 0x52, 0x06, 0x73, 0x68, 0x69, 0x70, 0x49, 0x64, 0x22, 0x3d, 0x0a, 0x0b, 0x55, 0x41, 0x44,
	0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x65, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x71, 0x4e,
	0x75, 0x6d, 0x18, 0x01, 0x20, 0x02, 0x28, 0x03, 0x52, 0x06, 0x73, 0x65, 0x71, 0x4e, 0x75, 0x6d,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x68, 0x69, 0x70, 0x49, 0x64, 0x18, 0x02, 0x20, 0x02, 0x28, 0x03,
	0x52, 0x06, 0x73, 0x68, 0x69, 0x70, 0x49, 0x64, 0x22, 0x53, 0x0a, 0x03, 0x45, 0x72, 0x72, 0x12,
	0x10, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x03, 0x65, 0x72,
	0x72, 0x12, 0x22, 0x0a, 0x0c, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x53, 0x65, 0x71, 0x4e, 0x75,
	0x6d, 0x18, 0x02, 0x20, 0x02, 0x28, 0x03, 0x52, 0x0c, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x53,
	0x65, 0x71, 0x4e, 0x75, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x71, 0x4e, 0x75, 0x6d, 0x18,
	0x03, 0x20, 0x02, 0x28, 0x03, 0x52, 0x06, 0x73, 0x65, 0x71, 0x4e, 0x75, 0x6d, 0x42, 0x03, 0x5a,
	0x01, 0x2e,
}

var (
	file_ua_proto_rawDescOnce sync.Once
	file_ua_proto_rawDescData = file_ua_proto_rawDesc
)

func file_ua_proto_rawDescGZIP() []byte {
	file_ua_proto_rawDescOnce.Do(func() {
		file_ua_proto_rawDescData = protoimpl.X.CompressGZIP(file_ua_proto_rawDescData)
	})
	return file_ua_proto_rawDescData
}

var file_ua_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_ua_proto_goTypes = []interface{}{
	(*AUCommand)(nil),        // 0: pb.AUCommand
	(*UACommand)(nil),        // 1: pb.UACommand
	(*UAstart)(nil),          // 2: pb.UAstart
	(*AUPickupRequest)(nil),  // 3: pb.AUPickupRequest
	(*UALoadRequest)(nil),    // 4: pb.UALoadRequest
	(*AUDeliverRequest)(nil), // 5: pb.AUDeliverRequest
	(*UADelivered)(nil),      // 6: pb.UADelivered
	(*Err)(nil),              // 7: pb.Err
}
var file_ua_proto_depIdxs = []int32{
	3, // 0: pb.AUCommand.pickupRequests:type_name -> pb.AUPickupRequest
	5, // 1: pb.AUCommand.deliverRequests:type_name -> pb.AUDeliverRequest
	7, // 2: pb.AUCommand.error:type_name -> pb.Err
	4, // 3: pb.UACommand.loadRequests:type_name -> pb.UALoadRequest
	6, // 4: pb.UACommand.delivered:type_name -> pb.UADelivered
	7, // 5: pb.UACommand.error:type_name -> pb.Err
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_ua_proto_init() }
func file_ua_proto_init() {
	if File_ua_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ua_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AUCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ua_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UACommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ua_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UAstart); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ua_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AUPickupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ua_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UALoadRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ua_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AUDeliverRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ua_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UADelivered); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ua_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Err); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ua_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ua_proto_goTypes,
		DependencyIndexes: file_ua_proto_depIdxs,
		MessageInfos:      file_ua_proto_msgTypes,
	}.Build()
	File_ua_proto = out.File
	file_ua_proto_rawDesc = nil
	file_ua_proto_goTypes = nil
	file_ua_proto_depIdxs = nil
}
