// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: ups.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UInitTruck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id *int32 `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	X  *int32 `protobuf:"varint,2,req,name=x" json:"x,omitempty"`
	Y  *int32 `protobuf:"varint,3,req,name=y" json:"y,omitempty"`
}

func (x *UInitTruck) Reset() {
	*x = UInitTruck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ups_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UInitTruck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UInitTruck) ProtoMessage() {}

func (x *UInitTruck) ProtoReflect() protoreflect.Message {
	mi := &file_ups_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UInitTruck.ProtoReflect.Descriptor instead.
func (*UInitTruck) Descriptor() ([]byte, []int) {
	return file_ups_proto_rawDescGZIP(), []int{0}
}

func (x *UInitTruck) GetId() int32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *UInitTruck) GetX() int32 {
	if x != nil && x.X != nil {
		return *x.X
	}
	return 0
}

func (x *UInitTruck) GetY() int32 {
	if x != nil && x.Y != nil {
		return *x.Y
	}
	return 0
}

type UConnect struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Worldid  *int64        `protobuf:"varint,1,opt,name=worldid" json:"worldid,omitempty"`
	Trucks   []*UInitTruck `protobuf:"bytes,2,rep,name=trucks" json:"trucks,omitempty"`
	IsAmazon *bool         `protobuf:"varint,3,req,name=isAmazon" json:"isAmazon,omitempty"`
}

func (x *UConnect) Reset() {
	*x = UConnect{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ups_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UConnect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UConnect) ProtoMessage() {}

func (x *UConnect) ProtoReflect() protoreflect.Message {
	mi := &file_ups_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UConnect.ProtoReflect.Descriptor instead.
func (*UConnect) Descriptor() ([]byte, []int) {
	return file_ups_proto_rawDescGZIP(), []int{1}
}

func (x *UConnect) GetWorldid() int64 {
	if x != nil && x.Worldid != nil {
		return *x.Worldid
	}
	return 0
}

func (x *UConnect) GetTrucks() []*UInitTruck {
	if x != nil {
		return x.Trucks
	}
	return nil
}

func (x *UConnect) GetIsAmazon() bool {
	if x != nil && x.IsAmazon != nil {
		return *x.IsAmazon
	}
	return false
}

type UConnected struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Worldid *int64  `protobuf:"varint,1,req,name=worldid" json:"worldid,omitempty"`
	Result  *string `protobuf:"bytes,2,req,name=result" json:"result,omitempty"`
}

func (x *UConnected) Reset() {
	*x = UConnected{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ups_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UConnected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UConnected) ProtoMessage() {}

func (x *UConnected) ProtoReflect() protoreflect.Message {
	mi := &file_ups_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UConnected.ProtoReflect.Descriptor instead.
func (*UConnected) Descriptor() ([]byte, []int) {
	return file_ups_proto_rawDescGZIP(), []int{2}
}

func (x *UConnected) GetWorldid() int64 {
	if x != nil && x.Worldid != nil {
		return *x.Worldid
	}
	return 0
}

func (x *UConnected) GetResult() string {
	if x != nil && x.Result != nil {
		return *x.Result
	}
	return ""
}

type UGoPickup struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Truckid *int32 `protobuf:"varint,1,req,name=truckid" json:"truckid,omitempty"`
	Whid    *int32 `protobuf:"varint,2,req,name=whid" json:"whid,omitempty"`
	Seqnum  *int64 `protobuf:"varint,3,req,name=seqnum" json:"seqnum,omitempty"`
}

func (x *UGoPickup) Reset() {
	*x = UGoPickup{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ups_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UGoPickup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UGoPickup) ProtoMessage() {}

func (x *UGoPickup) ProtoReflect() protoreflect.Message {
	mi := &file_ups_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UGoPickup.ProtoReflect.Descriptor instead.
func (*UGoPickup) Descriptor() ([]byte, []int) {
	return file_ups_proto_rawDescGZIP(), []int{3}
}

func (x *UGoPickup) GetTruckid() int32 {
	if x != nil && x.Truckid != nil {
		return *x.Truckid
	}
	return 0
}

func (x *UGoPickup) GetWhid() int32 {
	if x != nil && x.Whid != nil {
		return *x.Whid
	}
	return 0
}

func (x *UGoPickup) GetSeqnum() int64 {
	if x != nil && x.Seqnum != nil {
		return *x.Seqnum
	}
	return 0
}

type UFinished struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Truckid *int32  `protobuf:"varint,1,req,name=truckid" json:"truckid,omitempty"`
	X       *int32  `protobuf:"varint,2,req,name=x" json:"x,omitempty"`
	Y       *int32  `protobuf:"varint,3,req,name=y" json:"y,omitempty"`
	Status  *string `protobuf:"bytes,4,req,name=status" json:"status,omitempty"`
	Seqnum  *int64  `protobuf:"varint,5,req,name=seqnum" json:"seqnum,omitempty"`
}

func (x *UFinished) Reset() {
	*x = UFinished{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ups_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UFinished) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UFinished) ProtoMessage() {}

func (x *UFinished) ProtoReflect() protoreflect.Message {
	mi := &file_ups_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UFinished.ProtoReflect.Descriptor instead.
func (*UFinished) Descriptor() ([]byte, []int) {
	return file_ups_proto_rawDescGZIP(), []int{4}
}

func (x *UFinished) GetTruckid() int32 {
	if x != nil && x.Truckid != nil {
		return *x.Truckid
	}
	return 0
}

func (x *UFinished) GetX() int32 {
	if x != nil && x.X != nil {
		return *x.X
	}
	return 0
}

func (x *UFinished) GetY() int32 {
	if x != nil && x.Y != nil {
		return *x.Y
	}
	return 0
}

func (x *UFinished) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

func (x *UFinished) GetSeqnum() int64 {
	if x != nil && x.Seqnum != nil {
		return *x.Seqnum
	}
	return 0
}

type UDeliveryMade struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Truckid   *int32 `protobuf:"varint,1,req,name=truckid" json:"truckid,omitempty"`
	Packageid *int64 `protobuf:"varint,2,req,name=packageid" json:"packageid,omitempty"`
	Seqnum    *int64 `protobuf:"varint,3,req,name=seqnum" json:"seqnum,omitempty"`
}

func (x *UDeliveryMade) Reset() {
	*x = UDeliveryMade{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ups_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UDeliveryMade) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UDeliveryMade) ProtoMessage() {}

func (x *UDeliveryMade) ProtoReflect() protoreflect.Message {
	mi := &file_ups_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UDeliveryMade.ProtoReflect.Descriptor instead.
func (*UDeliveryMade) Descriptor() ([]byte, []int) {
	return file_ups_proto_rawDescGZIP(), []int{5}
}

func (x *UDeliveryMade) GetTruckid() int32 {
	if x != nil && x.Truckid != nil {
		return *x.Truckid
	}
	return 0
}

func (x *UDeliveryMade) GetPackageid() int64 {
	if x != nil && x.Packageid != nil {
		return *x.Packageid
	}
	return 0
}

func (x *UDeliveryMade) GetSeqnum() int64 {
	if x != nil && x.Seqnum != nil {
		return *x.Seqnum
	}
	return 0
}

type UDeliveryLocation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Packageid *int64 `protobuf:"varint,1,req,name=packageid" json:"packageid,omitempty"`
	X         *int32 `protobuf:"varint,2,req,name=x" json:"x,omitempty"`
	Y         *int32 `protobuf:"varint,3,req,name=y" json:"y,omitempty"`
}

func (x *UDeliveryLocation) Reset() {
	*x = UDeliveryLocation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ups_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UDeliveryLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UDeliveryLocation) ProtoMessage() {}

func (x *UDeliveryLocation) ProtoReflect() protoreflect.Message {
	mi := &file_ups_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UDeliveryLocation.ProtoReflect.Descriptor instead.
func (*UDeliveryLocation) Descriptor() ([]byte, []int) {
	return file_ups_proto_rawDescGZIP(), []int{6}
}

func (x *UDeliveryLocation) GetPackageid() int64 {
	if x != nil && x.Packageid != nil {
		return *x.Packageid
	}
	return 0
}

func (x *UDeliveryLocation) GetX() int32 {
	if x != nil && x.X != nil {
		return *x.X
	}
	return 0
}

func (x *UDeliveryLocation) GetY() int32 {
	if x != nil && x.Y != nil {
		return *x.Y
	}
	return 0
}

type UGoDeliver struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Truckid  *int32               `protobuf:"varint,1,req,name=truckid" json:"truckid,omitempty"`
	Packages []*UDeliveryLocation `protobuf:"bytes,2,rep,name=packages" json:"packages,omitempty"`
	Seqnum   *int64               `protobuf:"varint,3,req,name=seqnum" json:"seqnum,omitempty"`
}

func (x *UGoDeliver) Reset() {
	*x = UGoDeliver{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ups_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UGoDeliver) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UGoDeliver) ProtoMessage() {}

func (x *UGoDeliver) ProtoReflect() protoreflect.Message {
	mi := &file_ups_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UGoDeliver.ProtoReflect.Descriptor instead.
func (*UGoDeliver) Descriptor() ([]byte, []int) {
	return file_ups_proto_rawDescGZIP(), []int{7}
}

func (x *UGoDeliver) GetTruckid() int32 {
	if x != nil && x.Truckid != nil {
		return *x.Truckid
	}
	return 0
}

func (x *UGoDeliver) GetPackages() []*UDeliveryLocation {
	if x != nil {
		return x.Packages
	}
	return nil
}

func (x *UGoDeliver) GetSeqnum() int64 {
	if x != nil && x.Seqnum != nil {
		return *x.Seqnum
	}
	return 0
}

type UErr struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Err          *string `protobuf:"bytes,1,req,name=err" json:"err,omitempty"`
	Originseqnum *int64  `protobuf:"varint,2,req,name=originseqnum" json:"originseqnum,omitempty"`
	Seqnum       *int64  `protobuf:"varint,3,req,name=seqnum" json:"seqnum,omitempty"`
}

func (x *UErr) Reset() {
	*x = UErr{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ups_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UErr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UErr) ProtoMessage() {}

func (x *UErr) ProtoReflect() protoreflect.Message {
	mi := &file_ups_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UErr.ProtoReflect.Descriptor instead.
func (*UErr) Descriptor() ([]byte, []int) {
	return file_ups_proto_rawDescGZIP(), []int{8}
}

func (x *UErr) GetErr() string {
	if x != nil && x.Err != nil {
		return *x.Err
	}
	return ""
}

func (x *UErr) GetOriginseqnum() int64 {
	if x != nil && x.Originseqnum != nil {
		return *x.Originseqnum
	}
	return 0
}

func (x *UErr) GetSeqnum() int64 {
	if x != nil && x.Seqnum != nil {
		return *x.Seqnum
	}
	return 0
}

type UQuery struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Truckid *int32 `protobuf:"varint,1,req,name=truckid" json:"truckid,omitempty"`
	Seqnum  *int64 `protobuf:"varint,2,req,name=seqnum" json:"seqnum,omitempty"`
}

func (x *UQuery) Reset() {
	*x = UQuery{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ups_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UQuery) ProtoMessage() {}

func (x *UQuery) ProtoReflect() protoreflect.Message {
	mi := &file_ups_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UQuery.ProtoReflect.Descriptor instead.
func (*UQuery) Descriptor() ([]byte, []int) {
	return file_ups_proto_rawDescGZIP(), []int{9}
}

func (x *UQuery) GetTruckid() int32 {
	if x != nil && x.Truckid != nil {
		return *x.Truckid
	}
	return 0
}

func (x *UQuery) GetSeqnum() int64 {
	if x != nil && x.Seqnum != nil {
		return *x.Seqnum
	}
	return 0
}

type UTruck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Truckid *int32  `protobuf:"varint,1,req,name=truckid" json:"truckid,omitempty"`
	Status  *string `protobuf:"bytes,2,req,name=status" json:"status,omitempty"`
	X       *int32  `protobuf:"varint,3,req,name=x" json:"x,omitempty"`
	Y       *int32  `protobuf:"varint,4,req,name=y" json:"y,omitempty"`
	Seqnum  *int64  `protobuf:"varint,5,req,name=seqnum" json:"seqnum,omitempty"`
}

func (x *UTruck) Reset() {
	*x = UTruck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ups_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UTruck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UTruck) ProtoMessage() {}

func (x *UTruck) ProtoReflect() protoreflect.Message {
	mi := &file_ups_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UTruck.ProtoReflect.Descriptor instead.
func (*UTruck) Descriptor() ([]byte, []int) {
	return file_ups_proto_rawDescGZIP(), []int{10}
}

func (x *UTruck) GetTruckid() int32 {
	if x != nil && x.Truckid != nil {
		return *x.Truckid
	}
	return 0
}

func (x *UTruck) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

func (x *UTruck) GetX() int32 {
	if x != nil && x.X != nil {
		return *x.X
	}
	return 0
}

func (x *UTruck) GetY() int32 {
	if x != nil && x.Y != nil {
		return *x.Y
	}
	return 0
}

func (x *UTruck) GetSeqnum() int64 {
	if x != nil && x.Seqnum != nil {
		return *x.Seqnum
	}
	return 0
}

type UCommands struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pickups    []*UGoPickup  `protobuf:"bytes,1,rep,name=pickups" json:"pickups,omitempty"`
	Deliveries []*UGoDeliver `protobuf:"bytes,2,rep,name=deliveries" json:"deliveries,omitempty"`
	Simspeed   *uint32       `protobuf:"varint,3,opt,name=simspeed" json:"simspeed,omitempty"`
	Disconnect *bool         `protobuf:"varint,4,opt,name=disconnect" json:"disconnect,omitempty"`
	Queries    []*UQuery     `protobuf:"bytes,5,rep,name=queries" json:"queries,omitempty"`
	Acks       []int64       `protobuf:"varint,6,rep,name=acks" json:"acks,omitempty"`
}

func (x *UCommands) Reset() {
	*x = UCommands{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ups_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UCommands) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UCommands) ProtoMessage() {}

func (x *UCommands) ProtoReflect() protoreflect.Message {
	mi := &file_ups_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UCommands.ProtoReflect.Descriptor instead.
func (*UCommands) Descriptor() ([]byte, []int) {
	return file_ups_proto_rawDescGZIP(), []int{11}
}

func (x *UCommands) GetPickups() []*UGoPickup {
	if x != nil {
		return x.Pickups
	}
	return nil
}

func (x *UCommands) GetDeliveries() []*UGoDeliver {
	if x != nil {
		return x.Deliveries
	}
	return nil
}

func (x *UCommands) GetSimspeed() uint32 {
	if x != nil && x.Simspeed != nil {
		return *x.Simspeed
	}
	return 0
}

func (x *UCommands) GetDisconnect() bool {
	if x != nil && x.Disconnect != nil {
		return *x.Disconnect
	}
	return false
}

func (x *UCommands) GetQueries() []*UQuery {
	if x != nil {
		return x.Queries
	}
	return nil
}

func (x *UCommands) GetAcks() []int64 {
	if x != nil {
		return x.Acks
	}
	return nil
}

type UResponses struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Completions []*UFinished     `protobuf:"bytes,1,rep,name=completions" json:"completions,omitempty"`
	Delivered   []*UDeliveryMade `protobuf:"bytes,2,rep,name=delivered" json:"delivered,omitempty"`
	Finished    *bool            `protobuf:"varint,3,opt,name=finished" json:"finished,omitempty"`
	Acks        []int64          `protobuf:"varint,4,rep,name=acks" json:"acks,omitempty"`
	Truckstatus []*UTruck        `protobuf:"bytes,5,rep,name=truckstatus" json:"truckstatus,omitempty"`
	Error       []*UErr          `protobuf:"bytes,6,rep,name=error" json:"error,omitempty"`
}

func (x *UResponses) Reset() {
	*x = UResponses{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ups_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UResponses) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UResponses) ProtoMessage() {}

func (x *UResponses) ProtoReflect() protoreflect.Message {
	mi := &file_ups_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UResponses.ProtoReflect.Descriptor instead.
func (*UResponses) Descriptor() ([]byte, []int) {
	return file_ups_proto_rawDescGZIP(), []int{12}
}

func (x *UResponses) GetCompletions() []*UFinished {
	if x != nil {
		return x.Completions
	}
	return nil
}

func (x *UResponses) GetDelivered() []*UDeliveryMade {
	if x != nil {
		return x.Delivered
	}
	return nil
}

func (x *UResponses) GetFinished() bool {
	if x != nil && x.Finished != nil {
		return *x.Finished
	}
	return false
}

func (x *UResponses) GetAcks() []int64 {
	if x != nil {
		return x.Acks
	}
	return nil
}

func (x *UResponses) GetTruckstatus() []*UTruck {
	if x != nil {
		return x.Truckstatus
	}
	return nil
}

func (x *UResponses) GetError() []*UErr {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_ups_proto protoreflect.FileDescriptor

var file_ups_proto_rawDesc = []byte{
	0x0a, 0x09, 0x75, 0x70, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22,
	0x38, 0x0a, 0x0a, 0x55, 0x49, 0x6e, 0x69, 0x74, 0x54, 0x72, 0x75, 0x63, 0x6b, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x02, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x0c, 0x0a,
	0x01, 0x78, 0x18, 0x02, 0x20, 0x02, 0x28, 0x05, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79,
	0x18, 0x03, 0x20, 0x02, 0x28, 0x05, 0x52, 0x01, 0x79, 0x22, 0x68, 0x0a, 0x08, 0x55, 0x43, 0x6f,
	0x6e, 0x6e, 0x65, 0x63, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x69, 0x64, 0x12,
	0x26, 0x0a, 0x06, 0x74, 0x72, 0x75, 0x63, 0x6b, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x55, 0x49, 0x6e, 0x69, 0x74, 0x54, 0x72, 0x75, 0x63, 0x6b, 0x52,
	0x06, 0x74, 0x72, 0x75, 0x63, 0x6b, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x73, 0x41, 0x6d, 0x61,
	0x7a, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x02, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x41, 0x6d, 0x61,
	0x7a, 0x6f, 0x6e, 0x22, 0x3e, 0x0a, 0x0a, 0x55, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x65,
	0x64, 0x12, 0x18, 0x0a, 0x07, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x69, 0x64, 0x18, 0x01, 0x20, 0x02,
	0x28, 0x03, 0x52, 0x07, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x02, 0x20, 0x02, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x22, 0x51, 0x0a, 0x09, 0x55, 0x47, 0x6f, 0x50, 0x69, 0x63, 0x6b, 0x75, 0x70,
	0x12, 0x18, 0x0a, 0x07, 0x74, 0x72, 0x75, 0x63, 0x6b, 0x69, 0x64, 0x18, 0x01, 0x20, 0x02, 0x28,
	0x05, 0x52, 0x07, 0x74, 0x72, 0x75, 0x63, 0x6b, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x77, 0x68,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x02, 0x28, 0x05, 0x52, 0x04, 0x77, 0x68, 0x69, 0x64, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x65, 0x71, 0x6e, 0x75, 0x6d, 0x18, 0x03, 0x20, 0x02, 0x28, 0x03, 0x52, 0x06,
	0x73, 0x65, 0x71, 0x6e, 0x75, 0x6d, 0x22, 0x71, 0x0a, 0x09, 0x55, 0x46, 0x69, 0x6e, 0x69, 0x73,
	0x68, 0x65, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x72, 0x75, 0x63, 0x6b, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x02, 0x28, 0x05, 0x52, 0x07, 0x74, 0x72, 0x75, 0x63, 0x6b, 0x69, 0x64, 0x12, 0x0c, 0x0a,
	0x01, 0x78, 0x18, 0x02, 0x20, 0x02, 0x28, 0x05, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79,
	0x18, 0x03, 0x20, 0x02, 0x28, 0x05, 0x52, 0x01, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x02, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x71, 0x6e, 0x75, 0x6d, 0x18, 0x05, 0x20, 0x02, 0x28,
	0x03, 0x52, 0x06, 0x73, 0x65, 0x71, 0x6e, 0x75, 0x6d, 0x22, 0x5f, 0x0a, 0x0d, 0x55, 0x44, 0x65,
	0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x4d, 0x61, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x72,
	0x75, 0x63, 0x6b, 0x69, 0x64, 0x18, 0x01, 0x20, 0x02, 0x28, 0x05, 0x52, 0x07, 0x74, 0x72, 0x75,
	0x63, 0x6b, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x02, 0x28, 0x03, 0x52, 0x09, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65,
	0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x71, 0x6e, 0x75, 0x6d, 0x18, 0x03, 0x20, 0x02,
	0x28, 0x03, 0x52, 0x06, 0x73, 0x65, 0x71, 0x6e, 0x75, 0x6d, 0x22, 0x4d, 0x0a, 0x11, 0x55, 0x44,
	0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x1c, 0x0a, 0x09, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x69, 0x64, 0x18, 0x01, 0x20, 0x02,
	0x28, 0x03, 0x52, 0x09, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x69, 0x64, 0x12, 0x0c, 0x0a,
	0x01, 0x78, 0x18, 0x02, 0x20, 0x02, 0x28, 0x05, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79,
	0x18, 0x03, 0x20, 0x02, 0x28, 0x05, 0x52, 0x01, 0x79, 0x22, 0x71, 0x0a, 0x0a, 0x55, 0x47, 0x6f,
	0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x72, 0x75, 0x63, 0x6b,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x02, 0x28, 0x05, 0x52, 0x07, 0x74, 0x72, 0x75, 0x63, 0x6b, 0x69,
	0x64, 0x12, 0x31, 0x0a, 0x08, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x55, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65,
	0x72, 0x79, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x70, 0x61, 0x63, 0x6b,
	0x61, 0x67, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x71, 0x6e, 0x75, 0x6d, 0x18, 0x03,
	0x20, 0x02, 0x28, 0x03, 0x52, 0x06, 0x73, 0x65, 0x71, 0x6e, 0x75, 0x6d, 0x22, 0x54, 0x0a, 0x04,
	0x55, 0x45, 0x72, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x01, 0x20, 0x02, 0x28,
	0x09, 0x52, 0x03, 0x65, 0x72, 0x72, 0x12, 0x22, 0x0a, 0x0c, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e,
	0x73, 0x65, 0x71, 0x6e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x02, 0x28, 0x03, 0x52, 0x0c, 0x6f, 0x72,
	0x69, 0x67, 0x69, 0x6e, 0x73, 0x65, 0x71, 0x6e, 0x75, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65,
	0x71, 0x6e, 0x75, 0x6d, 0x18, 0x03, 0x20, 0x02, 0x28, 0x03, 0x52, 0x06, 0x73, 0x65, 0x71, 0x6e,
	0x75, 0x6d, 0x22, 0x3a, 0x0a, 0x06, 0x55, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x18, 0x0a, 0x07,
	0x74, 0x72, 0x75, 0x63, 0x6b, 0x69, 0x64, 0x18, 0x01, 0x20, 0x02, 0x28, 0x05, 0x52, 0x07, 0x74,
	0x72, 0x75, 0x63, 0x6b, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x71, 0x6e, 0x75, 0x6d,
	0x18, 0x02, 0x20, 0x02, 0x28, 0x03, 0x52, 0x06, 0x73, 0x65, 0x71, 0x6e, 0x75, 0x6d, 0x22, 0x6e,
	0x0a, 0x06, 0x55, 0x54, 0x72, 0x75, 0x63, 0x6b, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x72, 0x75, 0x63,
	0x6b, 0x69, 0x64, 0x18, 0x01, 0x20, 0x02, 0x28, 0x05, 0x52, 0x07, 0x74, 0x72, 0x75, 0x63, 0x6b,
	0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x02,
	0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18,
	0x03, 0x20, 0x02, 0x28, 0x05, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x04, 0x20,
	0x02, 0x28, 0x05, 0x52, 0x01, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x71, 0x6e, 0x75, 0x6d,
	0x18, 0x05, 0x20, 0x02, 0x28, 0x03, 0x52, 0x06, 0x73, 0x65, 0x71, 0x6e, 0x75, 0x6d, 0x22, 0xda,
	0x01, 0x0a, 0x09, 0x55, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x12, 0x27, 0x0a, 0x07,
	0x70, 0x69, 0x63, 0x6b, 0x75, 0x70, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e,
	0x70, 0x62, 0x2e, 0x55, 0x47, 0x6f, 0x50, 0x69, 0x63, 0x6b, 0x75, 0x70, 0x52, 0x07, 0x70, 0x69,
	0x63, 0x6b, 0x75, 0x70, 0x73, 0x12, 0x2e, 0x0a, 0x0a, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72,
	0x69, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x55,
	0x47, 0x6f, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x52, 0x0a, 0x64, 0x65, 0x6c, 0x69, 0x76,
	0x65, 0x72, 0x69, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x69, 0x6d, 0x73, 0x70, 0x65, 0x65,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x73, 0x69, 0x6d, 0x73, 0x70, 0x65, 0x65,
	0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63,
	0x74, 0x12, 0x24, 0x0a, 0x07, 0x71, 0x75, 0x65, 0x72, 0x69, 0x65, 0x73, 0x18, 0x05, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x70, 0x62, 0x2e, 0x55, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x07,
	0x71, 0x75, 0x65, 0x72, 0x69, 0x65, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x63, 0x6b, 0x73, 0x18,
	0x06, 0x20, 0x03, 0x28, 0x03, 0x52, 0x04, 0x61, 0x63, 0x6b, 0x73, 0x22, 0xec, 0x01, 0x0a, 0x0a,
	0x55, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x73, 0x12, 0x2f, 0x0a, 0x0b, 0x63, 0x6f,
	0x6d, 0x70, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x55, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x52, 0x0b,
	0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x2f, 0x0a, 0x09, 0x64,
	0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x65, 0x64, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11,
	0x2e, 0x70, 0x62, 0x2e, 0x55, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x4d, 0x61, 0x64,
	0x65, 0x52, 0x09, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x65, 0x64, 0x12, 0x1a, 0x0a, 0x08,
	0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08,
	0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x63, 0x6b, 0x73,
	0x18, 0x04, 0x20, 0x03, 0x28, 0x03, 0x52, 0x04, 0x61, 0x63, 0x6b, 0x73, 0x12, 0x2c, 0x0a, 0x0b,
	0x74, 0x72, 0x75, 0x63, 0x6b, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0a, 0x2e, 0x70, 0x62, 0x2e, 0x55, 0x54, 0x72, 0x75, 0x63, 0x6b, 0x52, 0x0b, 0x74,
	0x72, 0x75, 0x63, 0x6b, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1e, 0x0a, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x55,
	0x45, 0x72, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x42, 0x03, 0x5a, 0x01, 0x2e,
}

var (
	file_ups_proto_rawDescOnce sync.Once
	file_ups_proto_rawDescData = file_ups_proto_rawDesc
)

func file_ups_proto_rawDescGZIP() []byte {
	file_ups_proto_rawDescOnce.Do(func() {
		file_ups_proto_rawDescData = protoimpl.X.CompressGZIP(file_ups_proto_rawDescData)
	})
	return file_ups_proto_rawDescData
}

var file_ups_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_ups_proto_goTypes = []interface{}{
	(*UInitTruck)(nil),        // 0: pb.UInitTruck
	(*UConnect)(nil),          // 1: pb.UConnect
	(*UConnected)(nil),        // 2: pb.UConnected
	(*UGoPickup)(nil),         // 3: pb.UGoPickup
	(*UFinished)(nil),         // 4: pb.UFinished
	(*UDeliveryMade)(nil),     // 5: pb.UDeliveryMade
	(*UDeliveryLocation)(nil), // 6: pb.UDeliveryLocation
	(*UGoDeliver)(nil),        // 7: pb.UGoDeliver
	(*UErr)(nil),              // 8: pb.UErr
	(*UQuery)(nil),            // 9: pb.UQuery
	(*UTruck)(nil),            // 10: pb.UTruck
	(*UCommands)(nil),         // 11: pb.UCommands
	(*UResponses)(nil),        // 12: pb.UResponses
}
var file_ups_proto_depIdxs = []int32{
	0,  // 0: pb.UConnect.trucks:type_name -> pb.UInitTruck
	6,  // 1: pb.UGoDeliver.packages:type_name -> pb.UDeliveryLocation
	3,  // 2: pb.UCommands.pickups:type_name -> pb.UGoPickup
	7,  // 3: pb.UCommands.deliveries:type_name -> pb.UGoDeliver
	9,  // 4: pb.UCommands.queries:type_name -> pb.UQuery
	4,  // 5: pb.UResponses.completions:type_name -> pb.UFinished
	5,  // 6: pb.UResponses.delivered:type_name -> pb.UDeliveryMade
	10, // 7: pb.UResponses.truckstatus:type_name -> pb.UTruck
	8,  // 8: pb.UResponses.error:type_name -> pb.UErr
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_ups_proto_init() }
func file_ups_proto_init() {
	if File_ups_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ups_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UInitTruck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ups_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UConnect); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ups_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UConnected); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ups_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UGoPickup); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ups_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UFinished); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ups_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UDeliveryMade); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ups_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UDeliveryLocation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ups_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UGoDeliver); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ups_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UErr); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ups_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UQuery); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ups_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UTruck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ups_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UCommands); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ups_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UResponses); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ups_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ups_proto_goTypes,
		DependencyIndexes: file_ups_proto_depIdxs,
		MessageInfos:      file_ups_proto_msgTypes,
	}.Build()
	File_ups_proto = out.File
	file_ups_proto_rawDesc = nil
	file_ups_proto_goTypes = nil
	file_ups_proto_depIdxs = nil
}
